#Use yml to avoid the Chinese Disorderly Code 
##Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 294127003
    driver-class-name: com.mysql.jdbc.Driver
  ##redis Configuration
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

##Mybatis Configuration
mybatis:
  type-aliases-package: com.vidi.demo.domain
  mapper-locations: classpath:mapper/*.xml

